version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - ai-service

  ai-service:
    build: ./ai-service
    ports:
      - "5001:5001"
    environment:
      - GEMINI_API_KEY=AIzaSyAeZlC7A_1JYVBUsYFGpAW4qs_2PbqpVFc